name: cardiotrace
version: '1.0.0'
config-version: 2

profile: cardiotrace

model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]
log-path:    "logs"
target-path: "target"
clean-targets: ["target", "logs"]

models:
  cardiotrace:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: staging
    mart:
      +materialized: table
      +schema: mart
