"""A concise research closeout, with every numerical claim read from results."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build(root=ROOT):
    def read(name):
        return json.loads((root / "reports" / name).read_text(encoding="utf-8"))
    desc, cohort, model, pce, learning = [read(n) for n in
        ["descriptive_results.json", "cohort_results.json", "model_results.json",
         "pce_results.json", "part4_learning_results.json"]]
    p1, p2 = desc["part1"], desc["part2"]
    gain = learning["arms"]["deltas"]["cox_wide"]
    form = learning["arms"]["deltas"]["gbm_p"]
    sbp = model["aetiologic_sbp_per_10mmhg"]
    rows = []
    for horizon, test in pce["primary"]["tests"].items():
        a, b = [test["metrics"][k] for k in ["1a_published_ascvd", "3_cardiotrace_refit"]]
        delta = test["delta_c_vs_published_pce"]["3_cardiotrace_refit"]
        rows.append(f"| {horizon} | {a['n']:,} | {a['c']:.4f} | {b['c']:.4f} | "
                    f"{delta['delta']:+.4f} ({delta['lo']:+.4f}, {delta['hi']:+.4f}) |")
    return f"""# Cardiovascular burden and mortality prediction in NHANES: research closeout

Generated by `scripts/render_research_summary.py` from committed result JSON.
This is a structured research summary, not a submitted manuscript.

## Background and objective

Describe cardiovascular disease burden over repeated NHANES surveys, examine
the post-pandemic deviation from the preceding trend, and evaluate prospective
CVD-mortality prediction and the relative contribution of variables and model
form. Preserve PCE as the prespecified historical prognostic benchmark.

## Methods

Burden and pandemic analyses use interview weights in adults aged 20 or older;
mortality analyses use examination weights for adults aged 40–79 without
baseline CVD. The prospective cohort covers 1999–2014, with mortality follow-up
through 2019. Training uses 1999–2004; later cycles evaluate ten- and five-year
risk. Cause-specific Cox models account for competing deaths when estimating
absolute risk. PCE comparisons use identical complete-case samples for all arms
and primary analyses include non-Hispanic White and Black participants.
Reported paired PCE intervals use 200 stratified PSU-bootstrap replicates
conditional on the fitted training models.

## Results

- **Burden:** {p1['n_adults']:,} adults across {p1['n_cycles']} cycles.
  Age-standardised prevalence was {100*p1['std_first']:.2f}% initially and
  {100*p1['std_last']:.2f}% in August 2021–August 2023. The pre-pandemic trend was
  {100*p1['std_slope_per_decade']:+.2f} percentage points per decade
  (95% interval {100*p1['std_slope_ci'][0]:+.2f} to {100*p1['std_slope_ci'][1]:+.2f});
  it does not establish a decline.
- **Pandemic deviation:** observed minus extrapolated prevalence was
  {100*p2['gap']:+.2f} percentage points
  ({100*p2['gap_ci'][0]:+.2f} to {100*p2['gap_ci'][1]:+.2f}).
  One redesigned post-pandemic survey cannot identify a pandemic causal effect.
- **Prospective cohort:** {cohort['n_participants']:,} participants,
  {cohort['cvd_deaths']:,} CVD deaths and {cohort['competing_deaths']:,} competing
  deaths over {cohort['person_years']:,.0f} person-years. Adjusted systolic BP is
  associated with mortality (HR {sbp['hr']:.4f} per 10 mmHg).
  The report presents R design-based intervals beside Python cluster-robust
  sensitivity intervals. The E2 completeness-weight sensitivity uses its exact
  fitted covariates; agreement does not resolve MNAR selection bias.
- **Variables versus form:** in the separate Part 4 comparison, adding the
  selected log-UACR feature changed weighted C by {gain['delta']:+.4f}
  ({gain['lo']:+.4f} to {gain['hi']:+.4f}); gradient boosting on the existing
  inputs changed C by {form['delta']:+.4f}
  ({form['lo']:+.4f} to {form['hi']:+.4f}). These findings apply to the tested
  feature sets and fitted models, not to all flexible modelling methods.

### Historical PCE benchmark

| Test horizon | Paired n | Published PCE weighted C | CardioTrace weighted C | Difference (95% interval) |
|---|---:|---:|---:|---|
""" + "\n".join(rows) + """

The data do not establish CardioTrace discrimination superiority to PCE at
either horizon. PCE targets hard ASCVD, including nonfatal events; this study
observes CVD mortality. The five-year comparison uses the original ten-year
PCE score only for ranking. Mortality baseline adaptations and same-input
refits are reported separately. Exploratory decision curves exclude the
published ASCVD probability and provide no clinical-benefit claim.

## Limitations and conclusion

The contribution is an auditable analysis of burden, prognosis, and a bounded
comparison of predictor sets and model form. Complete-case selection,
conditional uncertainty intervals, mortality rather than incidence,
public-use linkage perturbation, the four-year-weight deviation, and
pre-pandemic follow-up limit interpretation. The R cross-check covers the
original survey estimators, not the new PCE mortality adaptation.

Technical deliverables comprise generated reports, fitted benchmark parameters,
participant tables, code, regression tests, raw-input manifests, and a checked
reproduction snapshot. A full receipt establishes internal reproducibility,
not clinical validity. See `docs/reproducibility.md` for exact coverage.

**Publication declarations remain open:** authorship/contributions, institutional
ethics determination, funding, conflicts, registration, and patient/public
involvement must be supplied by the investigator. Do not infer negative
declarations from absence. The evidence map in `docs/tripod-checklist.md`
also identifies scientific analyses outside this completed scope.

Sources: `reports/descriptive_results.json`, `reports/cohort_results.json`,
`reports/model_results.json`, `reports/part4_learning_results.json`,
`reports/pce_results.json`. Design decisions: `docs/research-design.md`.
"""


if __name__ == "__main__":
    (ROOT / "docs/research-summary.md").write_text(build(), encoding="utf-8")
    print("Research summary rebuilt from current result JSON")
